### ISSUE TITLE
numpy.float error in newer versions of numpy

### ISSUE THREAD

**Issue by rgasper** [bp-kelley/descriptastorus#23]
newer versions of numpy don't support `numpy.float`.

Getting this error when using descriptastorus w/ `numpy==1.24.3`:

```
Traceback (most recent call last):
  File "/opt/conda/envs/env/lib/python3.8/site-packages/descriptastorus/descriptors/rdDescriptors.py", line 336, in applyFunc
    return FUNCS[name](m)
  File "/opt/conda/envs/env/lib/python3.8/site-packages/rdkit/Chem/GraphDescriptors.py", line 124, in Ipc
    cPoly = abs(Graphs.CharacteristicPolynomial(mol, adjMat))
  File "/opt/conda/envs/env/lib/python3.8/site-packages/rdkit/Chem/Graphs.py", line 43, in CharacteristicPolynomial
    res = numpy.zeros(nAtoms + 1, numpy.float)
  File "/opt/conda/envs/env/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
```

**Comment by rgasper** [comment]
This is on descriptastorus version `2.5.0.23`. I'll try upgrading and see if that fixes the issue

**Comment by rgasper** [comment]
Also happening w/ version 2.6.1.

This is particularly problematic as if you use descriptastorus on a lot of molecules in a jupyter notebook, the number of error messages crashes the notebook!

**Comment by rgasper** [comment]
this isn't really descriptastorus' problem

**Comment by bp-kelley** [comment]
No, float should be used, the numpy.float has been deprecated for a while, I’ll update the build.

**Comment by rgasper** [comment]
well the error is in rdkit itself I realized

**Comment by rgasper** [comment]
oh lol you are also there and aware! Carry on

**Comment by bp-kelley** [comment]
I need to bump the rdkit and numpy versions :)
